### ISSUE TITLE
The if test is not working as expected

### ISSUE THREAD

**Issue by albrugnetti** [uclouvain/osis-portal#1158]
@htmfilho commented on [Tue Aug 08 2017](https://github.com/uclouvain/osis/issues/2716)

It tries to add a user to the group even with the test to check if the user is already in the group.
```
def _assign_group(person, group_name):
    """
    Assign the "person" to the group named "group_name"
    :param person: != none, an object person
    :param group_name: a string of a legit group
    :return: nothing
    """
    group = Group.objects.get(name=group_name)
    if person.user and \
            not person.user.groups.filter(name=group_name).exists():
        person.user.groups.add(group)
```

**Comment by albrugnetti** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/osis/VENV/lib/python3.4/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/home/osis/VENV/lib/python3.4/site-packages/osis_louvain_auth/authentication/shibboleth_auth.py", line 108, in process_request
    user = auth.authenticate(remote_user=username, user_infos=user_infos)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/osis/VENV/lib/python3.4/site-packages/osis_louvain_auth/authentication/shibboleth_auth.py", line 64, in authenticate
    user_updated_signal.send(sender=self.__class__, user=user, user_infos=user_infos)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/osis/www/html/osis_portal/base/models/signals.py", line 44, in update_person
    _add_person_to_group(person)
  File "/home/osis/www/html/osis_portal/base/models/signals.py", line 97, in _add_person_to_group
    _assign_group(person, "tutors")
  File "/home/osis/www/html/osis_portal/base/models/signals.py", line 114, in _assign_group
    person.user.groups.add(group)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/fields/related_descriptors.py", line 843, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/fields/related_descriptors.py", line 1004, in _add_items
    for obj_id in new_ids
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/query.py", line 450, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/query.py", line 1056, in _batched_insert
    using=self.db)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_groups_user_id_94350c0c_uniq"
DETAIL:  Key (user_id, group_id)=(6, 2) already exists.

**Comment by basmot** [comment]
Je ferme ce ticket et le PR associé. Voir description dans uclouvain/osis#2716.
